In [1]:
import numpy as np
import pandas as pd
students = np.random.randint(50,101,size=(50,5))
stu = pd.DataFrame(students,
             columns=['國文','英文','數學','地理','歷史'],
             index=[f'第{i}號' for i in range(1,51)]
             )
stu

       國文  英文   數學   地理  歷史
第1號    59  98   59   96  78
第2號    69  51   86   98  72
第3號    53  96   82   66  86
第4號    68  79   61   91  98
第5號    87  87   92  100  85
第6號    90  55   73   54  95
第7號    65  66   65   73  75
第8號    58  53   64   61  95
第9號    75  54   98   93  59
第10號   50  91   80   84  68
第11號   79  86   71   69  62
第12號   62  63   72   65  79
第13號   87  73   63   68  51
第14號   59  80   82   77  87
第15號   80  59   59   87  74
第16號   88  88   94   93  54
第17號   70  70   73   85  68
第18號   63  64   57   68  66
第19號   94  95   52   70  78
第20號   82  80   93   63  77
第21號   60  71   56   65  92
第22號   70  96   51   57  52
第23號   95  51   82   57  59
第24號   94  76   67   60  62
第25號   73  62   56   66  69
第26號   63  75   87   71  95
第27號   72  82   64   91  67
第28號   82  58   81   70  72
第29號   94  58   53  100  69
第30號  100  70   88   92  70
第31號   94  78   67   70  95
第32號   63  77   96   81  52
第33號   76  92   54   79  53
第34號   84  63   67   76  78
第35號   81  51   79   75  62
第36號   67  71   70   66  57
第37號   98  67  100   73  66
第38號   98  94   93   65  91
第39號   92  53   87   79  92
第40號   90  68   83   86  62
第41號   70  97   64   63  70
第42號   66  66   63   55  56
第43號   76  82   72   83  56
第44號   58  65   91   59  62
第45號   61  50   51   57  62
第46號   93  94   66   54  53
第47號   59  98   59   67  52
第48號   97  68   64   54  59
第49號   73  84   67   80  81
第50號   55  91   76   87  74

In [2]:
#Series
chines_series = stu['國文']
chines_series

第1號      59
第2號      69
第3號      53
第4號      68
第5號      87
第6號      90
第7號      65
第8號      58
第9號      75
第10號     50
第11號     79
第12號     62
第13號     87
第14號     59
第15號     80
第16號     88
第17號     70
第18號     63
第19號     94
第20號     82
第21號     60
第22號     70
第23號     95
第24號     94
第25號     73
第26號     63
第27號     72
第28號     82
第29號     94
第30號    100
第31號     94
第32號     63
第33號     76
第34號     84
第35號     81
第36號     67
第37號     98
第38號     98
第39號     92
第40號     90
第41號     70
第42號     66
第43號     76
第44號     58
第45號     61
第46號     93
第47號     59
第48號     97
第49號     73
第50號     55
Name: 國文, dtype: int64

In [7]:
chines_series['第49號'].tolist() #第49號國文的成積

np.int64(73)

In [4]:
chines_series[['第49號','第50號']] #第49號和50號的國文的成積

第49號    73
第50號    55
Name: 國文, dtype: int64

In [ ]:
chines_series[:5] #國文前5個學生的分數

In [10]:
stu.loc["第1號"]

國文    59
英文    98
數學    59
地理    96
歷史    78
Name: 第1號, dtype: int64

In [11]:
#第1號和第10號的學生
stu.loc[['第1號','第10號']]

      國文  英文  數學  地理  歷史
第1號   59  98  59  96  78
第10號  50  91  80  84  68

In [12]:
#前5個學生
stu.iloc[:5]
#後5個學生
stu.iloc[-5:]

      國文  英文  數學  地理  歷史
第46號  93  94  66  54  53
第47號  59  98  59  67  52
第48號  97  68  64  54  59
第49號  73  84  67  80  81
第50號  55  91  76  87  74